namespace dhive.core.Syntax
{
    public enum SyntaxKind{
        NumberToken,
        WhitespaceToken,
        PlusToken,
        MinusToken,
        StarToken,
        SlashToken,
        ExclamationToken,
        EqualEqualToken,
        ExclamationEqualToken,
        AmpersandAmpersandToken,
        PipePipeToken,
        OpenParenthesisToken,
        CloseParenthesisToken,
        EqualToken,
        NoneToken,
        EndOfFileToken,
        NumberExpression,
        BinaryExpression,
        LiteralExpression,
        UnaryExpression,
        FalseKeyword,
        TrueKeyword,
        IndentiferToken,
        ParenthesizeExpression,
        NameExpression,
        AssignmentExpression
    }
}
